### PR TITLE
[18681] fix table form styles

### PR DESCRIPTION
**Pull request by floriank**
This should address an issue reported in https://community.openproject.org/work_packages/18681

It also fixes some issues with the design of the backlogs.
I took the liberty of closing the coment in the master sass file properly

### CODE REVIEW

**Comment by NobodysNightmare** [comment]
At a viewport width of about ~1340px this happens to me:

wrap

**Comment by NobodysNightmare** [comment]
The problem initially reported (text overlapped by arrow) still exists, regardless of the resolution:

cut-off

I however found out that it even existed before. This still means it is a bug though and I am not sure if we can fix it easily, because it is a classical issue of screen width vs. arbitrary text being entered.

**Comment by NobodysNightmare** [comment]
This might in some parts overlap with my first comment, but I think the resizing behaviour for the subject textbox is wrong. On a low resolution you see the behaviour from my first comment (wrapping), on a high resolution you have lots of whitespace:

whitespace

edit: Probably it is flexbox to the rescue, but lucky me does not know the DOM of such a backlogs table ^^

**Comment by floriank** [comment]
@NobodysNightmare I implemented the percentage base width we discussed.

**Pull request merged**
