### PR TITLE
Fixes an issue with selects not being properly displayed

### PR DESCRIPTION
**Pull request by floriank**
Meets https://community.openproject.org/work_packages/18681

### CODE REVIEW

**Comment by ulferts** [comment]
This does not fix the problem in general. If the values get longer, they will also break the limit of now 130px width. Setting the "form--select" class will help, however there is a problem introduced in 387c10a4 which decreases the padding-right on the select from 1.5rem to 0.25rem.

**Comment by ulferts** [comment]
@floriank just stumbled over this. Any update?

**Comment by floriank** [comment]
Not yet.

**Comment by floriank** [comment]
Closing in need for an updated solution

**Pull request closed without merging**
