### PR TITLE
Skip Cross-site request forgery (CSRF) protection for show action

### PR DESCRIPTION
**Pull request by kgalli**
With Rails 4.1 Cross-site request forgery (CSRF) protection now covers GET requests with JavaScript responses, too. That is a problem for our implementation.

### CODE REVIEW

**Comment by basiszwo** [comment]
If I get it right no test covers this part :unamused: 
Question is, do we need it as we want to get rid of the view anyway ...

**Comment by kgalli** [comment]
My fix is only necessary because we are doing something very odd at least it feels to me that way. The `get` to the javascript should not be rendered by the `controller`. Instead it should be a simple asset. Yes we have the `project_id` as a dynamic value. But this is only necessary because the logic which adds `work_packages` or `stories` in this context does not retrieve the `project_id` from the URL. Which it could in my opinion.

So do we want to leave this as is and merge because we know we will get rid of this in the near future or do we want to invest the time to make it work as I think it should be implemented.

@basiszwo Unfortunately it is not that easy to write a test for this because CSRF is somehow ignored in our tests and right now I have no idea how to simply bypass that (test run only/always in combination with our core).

@basiszwo and @oliverguenther please advice what to do.

**Comment by kgalli** [comment]
As an addition: We could convert the whole dynamic javascript to a view helper or partial. Benefit would be we would save a request and the whole CSRF thing would be gone. Still questionable but maybe better than what we have right now.

**Comment by kgalli** [comment]
Ok we have the same problem with tasks to. So we have to adjust the `show.html.erb` for the `TaskBoards` too. Let us decide which way we want to go and I will adjust the mentioned files too.

**Comment by oliverguenther** [comment]
Works as expected and is an appropriate alternative to gon.

**Pull request merged**
