### PR TITLE
[18682] Taskboard not styled properly

### PR DESCRIPTION
**Pull request by HDinger**
aligned the columns by setting a different column-width

https://community.openproject.org/work_packages/18682

### CODE REVIEW

**Comment by HDinger** [comment]
@NobodysNightmare can you please have a look?

**Comment by NobodysNightmare** [comment]
Now we have a problem on the right hand side :(

image

I guess there will be no easy solution here, because the original solution is... unique...

**Comment by HDinger** [comment]
The current solution inserts the border on the right side elements again, which is necessary for an consistent width calculation. However as the solution before this doesn't work for all zoom factors, but the overflow at original size is vanished.

**Comment by NobodysNightmare** [comment]
looks best in IE ^^

**Pull request merged**
