### PR TITLE
Fix features and specs

### PR DESCRIPTION
**Pull request by NobodysNightmare**
This PR fixes wrongfully failing specs and features. I'd say it belongs to the topic of general house keeping: https://community.openproject.org/work_packages/18714

### CODE REVIEW

**Comment by floriank** [comment]
Let's ignore the @houndci for now, shall we?

**Comment by NobodysNightmare** [comment]
Yea, but I noticed one thing... gimme a second:

I should probably use the same selectors everywhere.

**Comment by NobodysNightmare** [comment]
Now I am really done ^^

**Comment by floriank** [comment]
Now that's a _premium PR_ if I ever saw one.

**Pull request merged**
