### PR TITLE
Fixed taskboard style

### PR DESCRIPTION
**Pull request by nickmessing**
https://community.openproject.org/work_packages/18682

### CODE REVIEW

**Comment by floriank** [comment]
Sorry for the late feedback.

The table looks okay, however, the column width input still seems to not be styled properly.

screenshot from 2015-03-13 15 06 51

Could we position the input to the right of the label?

**Comment by floriank** [comment]
@nickmessing ping?

**Comment by ulferts** [comment]
@nickmessing pong?

**Comment by nickmessing** [comment]
This one fixes the "Column width" https://github.com/finnlabs/openproject-backlogs/pull/127

**Comment by floriank** [comment]
Still seems broken to me.

@nickmessing could you please include the column width fix in this PR and have a look at it? I also introduced a toolbar component in opf/openproject#2771 which could be usable.

**Comment by floriank** [comment]
screenshot from 2015-04-09 14 56 55

**Pull request merged**
